// ...existing code...
class Jenny {
    // ...existing code...
    setPositionOnChair() {
        this.position = { x: 100, y: 200 }; // Adjust coordinates to match chair position
    }
}
// ...existing code...
